export const myWorks = [
  {
    id: 0,
    img: "https://i.imgur.com/bWg0Gf2.gif",
    title: "Vue Chat Proyect",
    description: "This SPA fetchs made with Vue, Pinia and Booststrap 5 uses Firebase to get functionalities of Authentication, Data Storage and Chat.",
    github: "https://github.com/derpmagician/fbvue3-exp",
    demo: "https://derpmagician.github.io/fbvue3-exp/",
  },
  {
    id: 1,
    img: "https://i.imgur.com/4JGWR3m.gif",
    title: "User Administrator",
    description: "This SPA fetchs an api and uses React, Routes and Redux to manipulate data and change users roles and location, it also has Auth0 authentication",
    github: "https://github.com/derpmagician/user-administration-react-redux",
    demo: "https://derpmagician.github.io/user-administration-react-redux/",
  },
  {
    id: 2,
    img: "https://i.imgur.com/1klVC95.png",
    title: "Shorten",
    description: "Link shortener made with Node, React y MongoDB, grabs the given url verifies if exist on the db and if doesnt then it gives you a short id, which can be used to access to the given url",
    github: "https://github.com/derpmagician/shorten",
    demo: null,
  },
  {
    id: 3,
    img: "https://i.imgur.com/pKBlia3.gif",
    title: "Image Filters",
    description: "Image Editor in React with a save feature manipulating the CSS with React",
    github: "https://github.com/derpmagician/react_img_filters",
    demo: "https://derpmagician.github.io/react_img_filters/",
  },
  {
    id: 4,
    img: "https://i.imgur.com/jg5jIGJ.gif",
    title: "Tower Defense Js",
    description: "Javascript vanilla game that uses the Canvas element of HTML and js classes to create the objects",
    github: "https://github.com/derpmagician/towerdefencejs",
    demo: "https://derpmagician.github.io/towerdefencejs/",
  },
  {
    id: 5,
    img: "https://i.imgur.com/F5OH2m1.png",
    title: "Space X Missions",
    description: "Fetching a Graphql API with React, UseEffect",
    github: "https://github.com/derpmagician/consumographqlspacex",
    demo: "https://derpmagician.github.io/consumographqlspacex/",
  },
  {
    id: 6,
    img: "https://i.imgur.com/hV20buP.gif",
    title: "Screen Saver Emulator",
    description: "Manipulates the CSS properties to draw the '3D' objects and only uses vanilla js to activate the timer for the screen to appear.",
    github: "https://github.com/derpmagician/ScreenSaver-Sim",
    demo: "https://derpmagician.github.io/ScreenSaver-Sim/",
  },
]
